import { defineConfig } from '@mikro-orm/postgresql';
import { type Options, ReflectMetadataProvider } from '@mikro-orm/core';
import { Migrator } from '@mikro-orm/migrations';
import 'reflect-metadata';
import { DatabaseConfig } from './database.config';

import {
  CurrencyEntity,
  CurrencyRateProviderEntity,
  CurrencyRatesHistoryEntity,
  ModerationRequestEntity,
  NotificationEntity,
  NotificationTemplateEntity,
  PaymentProviderEntity,
  PaymentTransactionEntity,
  ProviderCurrencyEntity,
  ProviderRoutingEntity,
  RateProviderCurrencyEntity,
  TrafficActionsEntity,
  TrafficOrderBalanceEntity,
  TrafficOrderEntity,
  TrafficSourceBalanceEntity,
  TrafficSourceBalanceHistoryEntity,
  TrafficSourceCategoryEntity,
  TrafficSourceEntity,
  TrafficTargetEntity,
  TrafficUserEntity,
  UserBalanceEntity,
  UserBalanceHistoryEntity,
  UserEntity,
  UserLastAuthEntity,
  UserRefLinkEntity,
  UserSettingsEntity,
  UserSourceVisitEntity,
} from '../entity';
import {
  TrafficActionsUsersEntity,
  TrafficOrderSourceEntity,
  TrafficOrderTargetEntity,
  TrafficSourceCategoriesEntity,
  TrafficTargetSourceEntity,
  TrafficTargetUsersEntity,
  UserTrafficOrderEntity,
  UserTrafficSourceEntity,
  UserTrafficTargetEntity,
} from '../entity/junction';

export function createMikroOrmConfig(config: DatabaseConfig): Options {
  return defineConfig({
    entities: [
      UserEntity,
      UserBalanceEntity,
      UserBalanceHistoryEntity,
      UserSettingsEntity,
      UserLastAuthEntity,
      UserRefLinkEntity,
      UserSourceVisitEntity,
      CurrencyEntity,
      CurrencyRatesHistoryEntity,
      CurrencyRateProviderEntity,
      RateProviderCurrencyEntity,
      PaymentTransactionEntity,
      TrafficSourceEntity,
      TrafficSourceBalanceEntity,
      TrafficSourceBalanceHistoryEntity,
      TrafficTargetEntity,
      TrafficUserEntity,
      TrafficOrderEntity,
      TrafficOrderBalanceEntity,
      TrafficActionsEntity,
      TrafficSourceCategoryEntity,
      TrafficActionsUsersEntity,
      TrafficOrderSourceEntity,
      TrafficOrderTargetEntity,
      UserTrafficTargetEntity,
      UserTrafficSourceEntity,
      UserTrafficOrderEntity,
      TrafficTargetSourceEntity,
      TrafficTargetUsersEntity,
      TrafficSourceCategoriesEntity,
      PaymentProviderEntity,
      ProviderCurrencyEntity,
      ProviderRoutingEntity,
      ModerationRequestEntity,
      NotificationEntity,
      NotificationTemplateEntity,
    ],
    host: config.host,
    port: config.port,
    dbName: config.dbName,
    user: config.user,
    password: config.password,
    metadataProvider: ReflectMetadataProvider,
    debug: config.debug,
    extensions: [Migrator],
    migrations: {
      path: config.migrations.path,
      tableName: config.migrations.tableName,
      transactional: config.migrations.transactional,
      disableForeignKeys: false,
      allOrNothing: config.migrations.allOrNothing,
      dropTables: false,
      safe: config.migrations.safe,
      snapshot: true,
      emit: config.migrations.emit,
    },
    schemaGenerator: {
      disableForeignKeys: false,
      createForeignKeyConstraints: true,
      ignoreSchema: [],
    },
  }) as Options;
}
