export enum BullQueue {
  BlockchainsSystemPush = 'blockchains-system-push',
  BlockchainsTransport = 'blockchains-transport',
  BotMainMenuPush = 'bot-main-menu-push',
  ChequesTask = 'cheques-tasks',
  ChatTask = 'chats-tasks',
  ErrorsLog = 'errors-log',
  P2pPush = 'p2p-push',
  Push = 'push',
  SystemPush = 'system-push',
  SystemTasks = 'system-tasks',
  UserBonusUpdater = 'user-bonus-updater',
  Webhooks = 'webhooks',
  SolanaBlocks = 'solana-blocks',
  DexMmBc = 'dex-mm-bc',
  DexMmMs = 'dex-mm-ms',
  VolumeTrading = 'volume-trading',
}
