import { HttpStatus } from '@nestjs/common';

const httpStatusNameRecord: Record<HttpStatus, string> = {
  [HttpStatus.CONTINUE]: 'Continue',
  [HttpStatus.SWITCHING_PROTOCOLS]: 'Switching protocols',
  [HttpStatus.PROCESSING]: 'Processing',
  [HttpStatus.EARLYHINTS]: 'Early hints',
  [HttpStatus.OK]: 'Ok',
  [HttpStatus.CREATED]: 'Created',
  [HttpStatus.ACCEPTED]: 'Accepted',
  [HttpStatus.NON_AUTHORITATIVE_INFORMATION]: 'Non-authoritative information',
  [HttpStatus.NO_CONTENT]: 'No content',
  [HttpStatus.RESET_CONTENT]: 'Reset content',
  [HttpStatus.PARTIAL_CONTENT]: 'Partial content',
  [HttpStatus.MULTI_STATUS]: 'Multi-status',
  [HttpStatus.ALREADY_REPORTED]: 'Already reported',
  210: 'Content different',
  [HttpStatus.AMBIGUOUS]: 'Ambiguous',
  [HttpStatus.MOVED_PERMANENTLY]: 'Moved permanently',
  [HttpStatus.FOUND]: 'Found',
  [HttpStatus.SEE_OTHER]: 'See other',
  [HttpStatus.NOT_MODIFIED]: 'Not modified',
  [HttpStatus.TEMPORARY_REDIRECT]: 'Temporary redirect',
  [HttpStatus.PERMANENT_REDIRECT]: 'Permanent redirect',
  [HttpStatus.BAD_REQUEST]: 'Bad request',
  [HttpStatus.UNAUTHORIZED]: 'Unauthorized',
  [HttpStatus.PAYMENT_REQUIRED]: 'Payment required',
  [HttpStatus.FORBIDDEN]: 'Forbidden',
  [HttpStatus.NOT_FOUND]: 'Not found',
  [HttpStatus.METHOD_NOT_ALLOWED]: 'Method not allowed',
  [HttpStatus.NOT_ACCEPTABLE]: 'Not acceptable',
  [HttpStatus.PROXY_AUTHENTICATION_REQUIRED]: 'Proxy authentication required',
  [HttpStatus.REQUEST_TIMEOUT]: 'Request timeout',
  [HttpStatus.CONFLICT]: 'Conflict',
  [HttpStatus.GONE]: 'Gone',
  [HttpStatus.LENGTH_REQUIRED]: 'Length required',
  [HttpStatus.PRECONDITION_FAILED]: 'Precondition failed',
  [HttpStatus.PAYLOAD_TOO_LARGE]: 'Payload too large',
  [HttpStatus.URI_TOO_LONG]: 'Uri too long',
  [HttpStatus.UNSUPPORTED_MEDIA_TYPE]: 'Unsupported media type',
  [HttpStatus.REQUESTED_RANGE_NOT_SATISFIABLE]: 'Requested range not satisfiable',
  [HttpStatus.EXPECTATION_FAILED]: 'Expectation failed',
  [HttpStatus.I_AM_A_TEAPOT]: 'I am a teapot',
  [HttpStatus.MISDIRECTED]: 'Misdirected request',
  [HttpStatus.UNPROCESSABLE_ENTITY]: 'Unprocessable entity',
  [HttpStatus.LOCKED]: 'Locked',
  [HttpStatus.FAILED_DEPENDENCY]: 'Failed dependency',
  [HttpStatus.PRECONDITION_REQUIRED]: 'Precondition required',
  [HttpStatus.TOO_MANY_REQUESTS]: 'Too many requests',
  456: 'Unrecoverable Error',
  [HttpStatus.INTERNAL_SERVER_ERROR]: 'Internal server error',
  [HttpStatus.NOT_IMPLEMENTED]: 'Not implemented',
  [HttpStatus.BAD_GATEWAY]: 'Bad gateway',
  [HttpStatus.SERVICE_UNAVAILABLE]: 'Service unavailable',
  [HttpStatus.GATEWAY_TIMEOUT]: 'Gateway timeout',
  [HttpStatus.HTTP_VERSION_NOT_SUPPORTED]: 'HTTP version not supported',
  507: 'Insufficient Storage',
  508: 'Loop Detected',
};

export function getHttpStatusName(status: HttpStatus): string {
  return httpStatusNameRecord[status] || `Unknown status (${status})`;
}
